version: '3'

services:
  api:
    container_name: bravi-api
    restart: always
    build: .
    ports:
      - 3000:80
    links:
      - database
    volumes:
      - ./src:/bravi-api/src
  database:
    container_name: mongodb
    image: mongo:3.6.1
    restart: always
    volumes:
      - ./data:/data
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - 3001:27017
    command:
      - mongod